### ISSUE TITLE
lamda value 

### ISSUE THREAD

**Issue by xiaoqiqiduo** [jsyoon0823/INVASE#1]
Hi Jinsung, I have a question about the lamda value. Using the default value of lamda, I cannot reproduce the results in the paper. I think the reason is that lamda has different values for different datasets. I wonder what is the lamda value for the six synthetic datasets.
Btw in main_invase.py, the type of lamda should be float rather than int. Thanks!

**Comment by jsyoon0823** [comment]
Thank you for this comment. (I fix the format of lamda to float).

To reproduce the results in Table 1, please use the following hyperparameters.
- Syn1: activation = relu, lamda = 0.1
- Syn2: activation = relu, lamda = 0.1
- Syn3: activation = selu, lamda = 0.1
- Syn4: activation = selu, lamda = 0.1 (Smaller TPR but still the best model)
- Syn5: activation = selu, lamda = 0.15
- Syn6: activation = selu, lamda = 0.1

For the general dataset, please do cross-validation (the criteria is the prediction accuracy of the predictor model) to select hyperparameters (especially lamda).

**Comment by xiaoqiqiduo** [comment]
Thanks for your reply. It works for the given hyperparameters.
