### ISSUE TITLE
Policy-gradient loss

### ISSUE THREAD

**Issue by DariusAf** [jsyoon0823/INVASE#2]
Hi,

I have a question regarding the [actor loss computation](https://github.com/jsyoon0823/INVASE/blob/c5cb78a0c098b2aee42bc7564893381326036bd0/invase.py#L119): it seems that the loss is different from the paper where the $l_0$ norm was used for the sampled mask and added to the reward. Here you seemingly add a $l_1$ on the feature selection probability estimates, acting as a sparse regularisation, but hence back-propagating something that was not intended from the derivation in the paper?

Why the difference, or is it something I misunderstood on the paper?

Thanks,
Darius

**Comment by jsyoon0823** [comment]
Yes. There are some differences between derivation of papers and the implementations.
However, the intuitions are the same.
L_0 norm in the paper and L_1 norm in the implementation have the same motivation: To regularize (minimize) the selected features. 
In this implementation, we just decoupled the regularization term and the reward term with the action probability.

**Comment by DariusAf** [comment]
Ok. Then, does a formulation perform better, or in certain cases?
Thanks,

**Comment by jsyoon0823** [comment]
It works similar in most cases (based on my experience)
